Repository OurPlanscape/Planscape, pull requests merged in 2022-12, with the labels that each got.

#166 Session storage/restoration for map view configuration
  src/interface/src/app/map/map.component.html
  src/interface/src/app/map/map.component.spec.ts
  src/interface/src/app/map/map.component.ts
  src/interface/src/app/services/session.service.spec.ts
  src/interface/src/app/services/session.service.ts
  src/interface/src/app/types/map.types.ts
Labels: enhancement

#167 Refactor leaflet methods into map-manager.ts
  src/interface/src/app/map/map-manager.ts
  src/interface/src/app/map/map.component.ts
Labels: enhancement

#176 Handle polygon deletion
  src/interface/src/app/map/map-manager.ts
  src/interface/src/app/map/map.component.scss
  src/interface/src/app/map/map.component.ts
Labels: enhancement

#179 Load boundary layers from config + lazy loading
  src/interface/src/app/map/map-manager.ts
  src/interface/src/app/map/map.component.html
  src/interface/src/app/map/map.component.spec.ts
  src/interface/src/app/map/map.component.ts
  src/interface/src/app/services/map.service.spec.ts
  src/interface/src/app/services/map.service.ts
  src/interface/src/app/services/session.service.ts
  src/interface/src/app/stringify-map-config.pipe.spec.ts
  src/interface/src/app/stringify-map-config.pipe.ts
  src/interface/src/app/types/data.types.ts
  src/interface/src/app/types/map.types.ts
Labels: enhancement

#186 Adjust drawing tool to multimaps
  src/interface/src/app/map/map-manager.ts
  src/interface/src/app/map/map.component.html
  src/interface/src/app/map/map.component.spec.ts
  src/interface/src/app/map/map.component.ts
  src/interface/src/app/types/map.types.ts
Labels: enhancement

#204 Miscellaneous small map updates
  src/interface/src/app/map/map-nameplate/map-nameplate.component.html
  src/interface/src/app/map/map-nameplate/map-nameplate.component.scss
  src/interface/src/app/map/map-nameplate/map-nameplate.component.spec.ts
  src/interface/src/app/map/map-nameplate/map-nameplate.component.ts
  src/interface/src/app/map/map.component.html
  src/interface/src/app/map/map.component.ts
  src/interface/src/app/material/material.module.ts
  src/interface/src/styles.scss
Labels: enhancement, frontend

#201 Map layer panel- add info button, hover state behavior, and callout function
  src/interface/src/app/app.module.ts
  src/interface/src/app/map/layer-info-card/layer-info-card.component.html
  src/interface/src/app/map/layer-info-card/layer-info-card.component.scss
  src/interface/src/app/map/layer-info-card/layer-info-card.component.spec.ts
  src/interface/src/app/map/layer-info-card/layer-info-card.component.ts
  src/interface/src/app/map/map.component.html
  src/interface/src/app/map/map.component.ts
  src/interface/src/app/material/material.module.ts
Labels: enhancement, frontend

#209 Fetch colormap values and update legend
  src/interface/src/app/map/map-manager.ts
  src/interface/src/app/map/map.component.html
  src/interface/src/app/map/map.component.scss
  src/interface/src/app/map/map.component.ts
  src/interface/src/app/services/map.service.spec.ts
  src/interface/src/app/services/map.service.ts
  src/interface/src/app/shared/legend/legend.component.html
  src/interface/src/app/shared/legend/legend.component.scss
  src/interface/src/app/shared/legend/legend.component.ts
  src/interface/src/app/types/data.types.ts
  src/interface/src/app/types/index.ts
  src/interface/src/app/types/legend.types.ts
  src/interface/src/app/types/map.types.ts
  src/planscape/config/colormap_config.py
Labels: enhancement, frontend, backend

#221 Allow switching between maps using tabs in single map view
  src/interface/src/app/map/map.component.html
Labels: bug, frontend

#213 Handle overlapping polygons when drawing
  src/interface/package-lock.json
  src/interface/package.json
  src/interface/src/app/map/map-manager.ts
  src/interface/src/app/map/map.component.spec.ts
  src/interface/src/app/map/map.component.ts
  src/interface/src/app/material/material.module.ts
  src/interface/src/styles.scss
Labels: enhancement

#228 Save map zoom and center in map view options
  src/interface/src/app/map/map-manager.ts
  src/interface/src/app/map/map.component.html
  src/interface/src/app/map/map.component.spec.ts
  src/interface/src/app/map/map.component.ts
  src/interface/src/app/services/session.service.spec.ts
  src/interface/src/app/types/map.types.ts
Labels: enhancement, frontend

#234 Fix loading indicator for projects
  src/interface/src/app/map/map.component.html
Labels: bug, frontend

#241 Feature flags module for frontend
  src/interface/src/app/app-routing.module.ts
  src/interface/src/app/app.module.ts
  src/interface/src/app/features/feature-flag.directive.spec.ts
  src/interface/src/app/features/feature-flag.directive.ts
  src/interface/src/app/features/feature.guard.ts
  src/interface/src/app/features/feature.service.spec.ts
  src/interface/src/app/features/feature.service.ts
  src/interface/src/app/features/features-config.ts
  src/interface/src/app/features/features.json
  src/interface/src/app/features/features.module.ts
  src/interface/src/app/navigation/navigation.component.html
  src/interface/tsconfig.json
Labels: enhancement, frontend

#235 Create barebones plan view
  src/interface/src/app/app-routing.module.ts
  src/interface/src/app/app.module.ts
  src/interface/src/app/map/map.component.spec.ts
  src/interface/src/app/map/map.component.ts
  src/interface/src/app/plan/plan.component.html
  src/interface/src/app/plan/plan.component.scss
  src/interface/src/app/plan/plan.component.spec.ts
  src/interface/src/app/plan/plan.component.ts
Labels: enhancement, frontend

#233 Display detail card for all boundaries and projects at clicked point on map
  src/interface/src/app/map/map-manager.ts
  src/interface/src/app/map/map.component.spec.ts
  src/interface/src/app/map/map.component.ts
  src/interface/src/app/map/project-card/project-card.component.html
  src/interface/src/app/map/project-card/project-card.component.scss
  src/interface/src/app/map/project-card/project-card.component.spec.ts
  src/interface/src/app/map/project-card/project-card.component.ts
  src/interface/src/app/types/map.types.ts
Labels: enhancement, frontend

#245 Add ability to upload an area
  src/interface/package-lock.json
  src/interface/package.json
  src/interface/src/app/map/map-manager.ts
  src/interface/src/app/map/map.component.html
  src/interface/src/app/map/map.component.scss
  src/interface/src/app/map/map.component.spec.ts
  src/interface/src/app/map/map.component.ts
  src/interface/src/app/shared/_variables.scss
  src/interface/src/app/shared/file-uploader/file-uploader.component.html
  src/interface/src/app/shared/file-uploader/file-uploader.component.scss
  src/interface/src/app/shared/file-uploader/file-uploader.component.spec.ts
  src/interface/src/app/shared/file-uploader/file-uploader.component.ts
  src/interface/src/app/shared/shared.module.ts
  src/interface/src/polyfills.ts
Labels: enhancement, frontend

#252 Improve create a plan flow and ui
  src/interface/src/app/map/map-manager.ts
  src/interface/src/app/map/map.component.html
  src/interface/src/app/map/map.component.scss
  src/interface/src/app/map/map.component.spec.ts
  src/interface/src/app/map/map.component.ts
  src/interface/src/app/shared/file-uploader/file-uploader.component.scss
  src/interface/src/styles.scss
Labels: enhancement, frontend

#250 Add Leaflet map to plan view
  src/interface/src/app/app.module.ts
  src/interface/src/app/plan/plan-map/plan-map.component.html
  src/interface/src/app/plan/plan-map/plan-map.component.scss
  src/interface/src/app/plan/plan-map/plan-map.component.spec.ts
  src/interface/src/app/plan/plan-map/plan-map.component.ts
  src/interface/src/app/plan/plan.component.html
  src/interface/src/app/plan/plan.component.scss
  src/interface/src/app/plan/plan.component.spec.ts
  src/interface/src/app/plan/plan.component.ts
Labels: enhancement, frontend

#261 Fix CSS for plan view map
  src/interface/src/app/plan/plan-map/plan-map.component.html
  src/interface/src/app/plan/plan-map/plan-map.component.scss
  src/interface/src/app/plan/plan.component.html
  src/interface/src/app/plan/plan.component.scss
Labels: bug, frontend

#263 Create the plan progress panel
  src/interface/src/app/app.module.ts
  src/interface/src/app/plan/plan.component.html
  src/interface/src/app/plan/plan.component.scss
  src/interface/src/app/plan/plan.component.spec.ts
  src/interface/src/app/plan/plan.component.ts
  src/interface/src/app/plan/progress-panel/progress-panel.component.html
  src/interface/src/app/plan/progress-panel/progress-panel.component.scss
  src/interface/src/app/plan/progress-panel/progress-panel.component.spec.ts
  src/interface/src/app/plan/progress-panel/progress-panel.component.ts
Labels: enhancement, frontend

#266 Scenario comparison tables in plan view
  src/interface/angular.json
  src/interface/src/app/app.module.ts
  src/interface/src/app/material/material.module.ts
  src/interface/src/app/plan/plan.component.html
  src/interface/src/app/plan/plan.component.scss
  src/interface/src/app/plan/plan.module.ts
  src/interface/src/app/plan/saved-scenarios/saved-scenarios.component.html
  src/interface/src/app/plan/saved-scenarios/saved-scenarios.component.scss
  src/interface/src/app/plan/saved-scenarios/saved-scenarios.component.spec.ts
  src/interface/src/app/plan/saved-scenarios/saved-scenarios.component.ts
  src/interface/src/app/plan/unsaved-scenarios/unsaved-scenarios.component.html
  src/interface/src/app/plan/unsaved-scenarios/unsaved-scenarios.component.scss
  src/interface/src/app/plan/unsaved-scenarios/unsaved-scenarios.component.spec.ts
  src/interface/src/app/plan/unsaved-scenarios/unsaved-scenarios.component.ts
  src/interface/src/app/types/plan.types.ts
Labels: enhancement, frontend

#264 Update sidebar design
  src/interface/src/app/navigation/navigation.component.html
  src/interface/src/app/navigation/navigation.component.scss
  src/interface/src/app/navigation/navigation.component.ts
  src/interface/src/styles.scss
Labels: enhancement, frontend
