Repository OurPlanscape/Planscape, pull requests merged in 2023-02, with the labels that each got.

#459 updated UI for step 1
  src/interface/src/app/plan/create-scenarios/create-scenarios-intro/create-scenarios-intro.component.html
  src/interface/src/app/plan/create-scenarios/create-scenarios-intro/create-scenarios-intro.component.scss
  src/interface/src/app/plan/create-scenarios/create-scenarios-intro/create-scenarios-intro.component.spec.ts
  src/interface/src/app/plan/create-scenarios/create-scenarios-intro/create-scenarios-intro.component.ts
Labels: enhancement, frontend, alpha phase 2

#460 Make plan stepper linear and update step 1
  src/interface/src/app/plan/create-scenarios/create-scenarios-intro/create-scenarios-intro.component.html
  src/interface/src/app/plan/create-scenarios/create-scenarios-intro/create-scenarios-intro.component.spec.ts
  src/interface/src/app/plan/create-scenarios/create-scenarios-intro/create-scenarios-intro.component.ts
  src/interface/src/app/plan/create-scenarios/create-scenarios.component.html
  src/interface/src/app/plan/create-scenarios/create-scenarios.component.scss
  src/interface/src/app/plan/create-scenarios/create-scenarios.component.spec.ts
  src/interface/src/app/plan/create-scenarios/create-scenarios.component.ts
Labels: bug, frontend, alpha phase 2

#466 Small tweak to app theme
  src/interface/src/app/plan/plan-navigation-bar/plan-navigation-bar.component.html
  src/interface/src/app/top-bar/top-bar.component.scss
  src/interface/src/styles.scss
Labels: enhancement, frontend

#461 Update plan step 2 ("set constraints")
  src/interface/src/app/plan/create-scenarios/constraints-panel/constraints-panel.component.html
  src/interface/src/app/plan/create-scenarios/constraints-panel/constraints-panel.component.scss
  src/interface/src/app/plan/create-scenarios/constraints-panel/constraints-panel.component.spec.ts
  src/interface/src/app/plan/create-scenarios/constraints-panel/constraints-panel.component.ts
  src/interface/src/app/plan/create-scenarios/create-scenarios.component.html
  src/interface/src/app/plan/create-scenarios/create-scenarios.component.spec.ts
  src/interface/src/app/plan/create-scenarios/create-scenarios.component.ts
Labels: bug, frontend, alpha phase 2

#462 Update plan step 3 ("select priorities")
  src/interface/src/app/map/map.component.html
  src/interface/src/app/map/map.component.scss
  src/interface/src/app/plan/create-scenarios/create-scenarios.component.html
  src/interface/src/app/plan/create-scenarios/create-scenarios.component.ts
  src/interface/src/app/plan/create-scenarios/set-priorities/set-priorities.component.html
  src/interface/src/app/plan/create-scenarios/set-priorities/set-priorities.component.scss
  src/interface/src/app/plan/create-scenarios/set-priorities/set-priorities.component.spec.ts
  src/interface/src/app/plan/create-scenarios/set-priorities/set-priorities.component.ts
  src/interface/src/app/shared/legend/legend.component.scss
  src/interface/src/app/shared/opacity-slider/opacity-slider.component.scss
Labels: bug, frontend, alpha phase 2

#467 Default selected region to Sierra Nevada
  src/interface/src/app/services/session.service.spec.ts
  src/interface/src/app/services/session.service.ts
Labels: frontend

#464 Add black overlay to saved scenario table
  src/interface/src/app/plan/plan-summary/saved-scenarios/saved-scenarios.component.html
  src/interface/src/app/plan/plan-summary/saved-scenarios/saved-scenarios.component.scss
  src/interface/src/app/plan/plan-summary/saved-scenarios/saved-scenarios.component.ts
Labels: enhancement, frontend, alpha phase 4

#469 Plan step 4: identify project areas
  src/interface/src/app/plan/create-scenarios/create-scenarios.component.html
  src/interface/src/app/plan/create-scenarios/create-scenarios.component.ts
  src/interface/src/app/plan/create-scenarios/identify-project-areas/identify-project-areas.component.html
  src/interface/src/app/plan/create-scenarios/identify-project-areas/identify-project-areas.component.scss
  src/interface/src/app/plan/create-scenarios/identify-project-areas/identify-project-areas.component.spec.ts
  src/interface/src/app/plan/create-scenarios/identify-project-areas/identify-project-areas.component.ts
  src/interface/src/app/plan/plan.module.ts
Labels: enhancement, frontend, alpha phase 3

#472 Plan step 4: draw uploaded project areas on map
  src/interface/src/app/plan/create-scenarios/create-scenarios.component.spec.ts
  src/interface/src/app/plan/create-scenarios/create-scenarios.component.ts
  src/interface/src/app/plan/create-scenarios/set-priorities/set-priorities.component.ts
  src/interface/src/app/plan/plan-map/plan-map.component.spec.ts
  src/interface/src/app/plan/plan-map/plan-map.component.ts
  src/interface/src/app/plan/plan.component.html
  src/interface/src/app/plan/plan.component.ts
Labels: enhancement, frontend, alpha phase 3

#474 Frontend: save project constraints and priorities
  src/interface/src/app/plan/create-scenarios/create-scenarios.component.spec.ts
  src/interface/src/app/plan/create-scenarios/create-scenarios.component.ts
  src/interface/src/app/plan/create-scenarios/set-priorities/set-priorities.component.spec.ts
  src/interface/src/app/plan/create-scenarios/set-priorities/set-priorities.component.ts
  src/interface/src/app/services/plan.service.spec.ts
  src/interface/src/app/services/plan.service.ts
  src/interface/src/app/types/plan.types.ts
  src/planscape/plan/views.py
Labels: enhancement, frontend, backend, alpha phase 3

#485 Update list_projects_for_plan to return condition display names
  src/planscape/plan/tests.py
  src/planscape/plan/views.py
Labels: backend, alpha phase 3

#484 Populate configuration table with real configurations
  src/interface/src/app/plan/plan-summary/plan-overview/plan-overview.component.html
  src/interface/src/app/plan/plan-summary/plan-overview/plan-overview.component.spec.ts
  src/interface/src/app/plan/plan-summary/scenario-configurations/scenario-configurations.component.html
  src/interface/src/app/plan/plan-summary/scenario-configurations/scenario-configurations.component.scss
  src/interface/src/app/plan/plan-summary/scenario-configurations/scenario-configurations.component.spec.ts
  src/interface/src/app/plan/plan-summary/scenario-configurations/scenario-configurations.component.ts
  src/interface/src/app/plan/plan-summary/unsaved-scenarios/unsaved-scenarios.component.html
  src/interface/src/app/plan/plan-summary/unsaved-scenarios/unsaved-scenarios.component.scss
  src/interface/src/app/plan/plan-summary/unsaved-scenarios/unsaved-scenarios.component.spec.ts
  src/interface/src/app/plan/plan-summary/unsaved-scenarios/unsaved-scenarios.component.ts
  src/interface/src/app/plan/plan-table/plan-table.component.html
  src/interface/src/app/plan/plan-table/plan-table.component.ts
  src/interface/src/app/plan/plan.component.spec.ts
  src/interface/src/app/plan/plan.module.ts
  src/interface/src/app/services/plan.service.spec.ts
  src/interface/src/app/services/plan.service.ts
  src/interface/src/app/types/plan.types.ts
Labels: frontend, alpha phase 3

#491 Map condition name to condition display name in frontend
  src/interface/src/app/plan/create-scenarios/create-scenarios.component.ts
  src/interface/src/app/plan/create-scenarios/set-priorities/set-priorities.component.spec.ts
  src/interface/src/app/plan/create-scenarios/set-priorities/set-priorities.component.ts
  src/interface/src/app/plan/plan-summary/scenario-configurations/scenario-configurations.component.html
  src/interface/src/app/plan/plan-summary/scenario-configurations/scenario-configurations.component.spec.ts
  src/interface/src/app/plan/plan-summary/scenario-configurations/scenario-configurations.component.ts
  src/interface/src/app/services/map.service.spec.ts
  src/interface/src/app/services/map.service.ts
  src/interface/src/app/types/plan.types.ts
  src/planscape/plan/tests.py
  src/planscape/plan/views.py
Labels: frontend, backend

#493 add ability to delete scenario configurations
  src/interface/src/app/plan/plan-summary/scenario-configurations/scenario-configurations.component.html
  src/interface/src/app/plan/plan-summary/scenario-configurations/scenario-configurations.component.spec.ts
  src/interface/src/app/plan/plan-summary/scenario-configurations/scenario-configurations.component.ts
  src/interface/src/app/services/plan.service.spec.ts
  src/interface/src/app/services/plan.service.ts
  src/planscape/plan/tests.py
  src/planscape/plan/urls.py
  src/planscape/plan/views.py
Labels: frontend, backend, alpha phase 3

#496 Plan Step 5 (UI only)
  src/interface/src/app/plan/create-scenarios/create-scenarios.component.html
  src/interface/src/app/plan/create-scenarios/create-scenarios.component.spec.ts
  src/interface/src/app/plan/create-scenarios/create-scenarios.component.ts
  src/interface/src/app/plan/create-scenarios/generate-scenarios/generate-scenarios.component.html
  src/interface/src/app/plan/create-scenarios/generate-scenarios/generate-scenarios.component.scss
  src/interface/src/app/plan/create-scenarios/generate-scenarios/generate-scenarios.component.spec.ts
  src/interface/src/app/plan/create-scenarios/generate-scenarios/generate-scenarios.component.ts
  src/interface/src/app/plan/plan.module.ts
Labels: enhancement, frontend, alpha phase 4

#495 Continue planning with an existing scenario config
  src/interface/src/app/plan/create-scenarios/create-scenarios.component.spec.ts
  src/interface/src/app/plan/create-scenarios/create-scenarios.component.ts
  src/interface/src/app/plan/create-scenarios/set-priorities/set-priorities.component.html
  src/interface/src/app/plan/create-scenarios/set-priorities/set-priorities.component.spec.ts
  src/interface/src/app/plan/create-scenarios/set-priorities/set-priorities.component.ts
  src/interface/src/app/plan/plan-summary/plan-overview/plan-overview.component.html
  src/interface/src/app/plan/plan-summary/plan-overview/plan-overview.component.spec.ts
  src/interface/src/app/plan/plan-summary/plan-overview/plan-overview.component.ts
  src/interface/src/app/plan/plan-summary/scenario-configurations/scenario-configurations.component.html
  src/interface/src/app/plan/plan-summary/scenario-configurations/scenario-configurations.component.spec.ts
  src/interface/src/app/plan/plan-summary/scenario-configurations/scenario-configurations.component.ts
  src/interface/src/app/plan/plan.component.html
  src/interface/src/app/plan/plan.component.spec.ts
  src/interface/src/app/plan/plan.component.ts
  src/interface/src/app/services/plan.service.spec.ts
  src/interface/src/app/services/plan.service.ts
  src/planscape/plan/tests.py
  src/planscape/plan/views.py
Labels: frontend, backend

#503 Refactor map control panel into its own component
  src/interface/src/app/app.module.ts
  src/interface/src/app/map/map-control-panel/map-control-panel.component.html
  src/interface/src/app/map/map-control-panel/map-control-panel.component.scss
  src/interface/src/app/map/map-control-panel/map-control-panel.component.spec.ts
  src/interface/src/app/map/map-control-panel/map-control-panel.component.ts
  src/interface/src/app/map/map.component.html
  src/interface/src/app/map/map.component.scss
  src/interface/src/app/map/map.component.spec.ts
  src/interface/src/app/map/map.component.ts
Labels: enhancement, frontend, alpha

#529 change plan metric scores to normalized
  src/interface/src/app/plan/create-scenarios/set-priorities/set-priorities.component.spec.ts
  src/interface/src/app/plan/create-scenarios/set-priorities/set-priorities.component.ts
Labels: enhancement, frontend, alpha

#533 add creation timestamp to projects
  src/interface/src/app/services/plan.service.spec.ts
  src/interface/src/app/services/plan.service.ts
  src/interface/src/app/types/plan.types.ts
  src/planscape/plan/migrations/0011_project_creation_time.py
  src/planscape/plan/models.py
  src/planscape/plan/tests.py
  src/planscape/plan/views.py
Labels: enhancement, frontend, backend, alpha

#528 Map control bugfixes and improvements
  src/interface/src/app/app.module.ts
  src/interface/src/app/map/map-control-panel/condition-tree/condition-tree.component.html
  src/interface/src/app/map/map-control-panel/condition-tree/condition-tree.component.scss
  src/interface/src/app/map/map-control-panel/condition-tree/condition-tree.component.spec.ts
  src/interface/src/app/map/map-control-panel/condition-tree/condition-tree.component.ts
  src/interface/src/app/map/map-control-panel/map-control-panel.component.html
  src/interface/src/app/map/map-control-panel/map-control-panel.component.scss
  src/interface/src/app/map/map-control-panel/map-control-panel.component.spec.ts
  src/interface/src/app/map/map-control-panel/map-control-panel.component.ts
Labels: enhancement, frontend, alpha

#534 Add super barebones Scenario Details view
  src/interface/src/app/plan/plan.component.html
  src/interface/src/app/plan/plan.component.scss
  src/interface/src/app/plan/scenario-details/scenario-details.component.html
  src/interface/src/app/plan/scenario-details/scenario-details.component.scss
Labels: enhancement, frontend

#530 swap config and saved scenario tables
  src/interface/src/app/plan/plan-summary/plan-overview/plan-overview.component.html
  src/interface/src/app/plan/plan-summary/plan-overview/plan-overview.component.spec.ts
  src/interface/src/app/plan/plan-summary/saved-scenarios/saved-scenarios.component.html
  src/interface/src/app/plan/plan-summary/scenario-configurations/scenario-configurations.component.html
  src/interface/src/app/plan/plan-summary/scenario-configurations/scenario-configurations.component.scss
Labels: enhancement, frontend, alpha

#536 fix constraints form logic
  src/interface/src/app/map/map-control-panel/map-control-panel.component.spec.ts
  src/interface/src/app/plan/create-scenarios/constraints-panel/constraints-panel.component.html
  src/interface/src/app/plan/create-scenarios/constraints-panel/constraints-panel.component.ts
  src/interface/src/app/plan/create-scenarios/create-scenarios.component.spec.ts
  src/interface/src/app/plan/create-scenarios/create-scenarios.component.ts
Labels: bug, frontend, alpha

#539 Combine score selection and priorities into same planning step
  src/interface/src/app/plan/create-scenarios/create-scenarios-intro/create-scenarios-intro.component.html
  src/interface/src/app/plan/create-scenarios/create-scenarios-intro/create-scenarios-intro.component.scss
  src/interface/src/app/plan/create-scenarios/create-scenarios-intro/create-scenarios-intro.component.spec.ts
  src/interface/src/app/plan/create-scenarios/create-scenarios-intro/create-scenarios-intro.component.ts
  src/interface/src/app/plan/create-scenarios/create-scenarios.component.html
  src/interface/src/app/plan/create-scenarios/create-scenarios.component.spec.ts
  src/interface/src/app/plan/create-scenarios/create-scenarios.component.ts
  src/interface/src/app/plan/create-scenarios/set-priorities/set-priorities.component.html
  src/interface/src/app/plan/create-scenarios/set-priorities/set-priorities.component.scss
  src/interface/src/app/plan/create-scenarios/set-priorities/set-priorities.component.spec.ts
  src/interface/src/app/plan/create-scenarios/set-priorities/set-priorities.component.ts
  src/interface/src/app/plan/plan.module.ts
  src/planscape/plan/views.py
Labels: enhancement, frontend, alpha

#542 add hover state for config and scenario table rows
  src/interface/src/app/plan/plan-summary/saved-scenarios/saved-scenarios.component.html
  src/interface/src/app/plan/plan-summary/saved-scenarios/saved-scenarios.component.scss
  src/interface/src/app/plan/plan-summary/scenario-configurations/scenario-configurations.component.html
  src/interface/src/app/plan/plan-summary/scenario-configurations/scenario-configurations.component.scss
Labels: enhancement, frontend

#544 Reuse and share components in Scenario Details view
  src/interface/src/app/plan/create-scenarios/create-scenarios.component.ts
  src/interface/src/app/plan/plan.component.html
  src/interface/src/app/plan/plan.component.ts
  src/interface/src/app/plan/scenario-details/scenario-details.component.html
  src/interface/src/app/plan/scenario-details/scenario-details.component.scss
  src/interface/src/app/plan/scenario-details/scenario-details.component.spec.ts
  src/interface/src/app/plan/scenario-details/scenario-details.component.ts
  src/interface/src/app/shared/animations.ts
Labels: frontend

#547 new terrain and satellite basemaps
  src/interface/src/app/map/map-manager.ts
  src/interface/src/app/map/map.component.ts
  src/interface/src/styles.scss
Labels: bug, frontend

#549 fix layer control tab labels
  src/interface/src/app/map/map-control-panel/map-control-panel.component.html
Labels: frontend

#550 map legend updates for usability
  src/interface/src/app/map/layer-info-card/layer-info-card.component.ts
  src/interface/src/app/map/map-control-panel/map-control-panel.component.html
  src/interface/src/app/map/map-control-panel/map-control-panel.component.scss
  src/interface/src/app/map/map-control-panel/map-control-panel.component.ts
  src/interface/src/app/map/map.component.html
  src/interface/src/app/plan/create-scenarios/set-priorities/set-priorities.component.scss
  src/interface/src/app/shared/legend/legend.component.html
  src/interface/src/app/shared/legend/legend.component.scss
  src/interface/src/app/shared/legend/legend.component.ts
  src/interface/src/app/shared/opacity-slider/opacity-slider.component.html
Labels: frontend, alpha

#558 fix frontend unit test warnings and errors
  src/interface/src/app/map/map-control-panel/condition-tree/condition-tree.component.spec.ts
  src/interface/src/app/map/map-control-panel/map-control-panel.component.spec.ts
  src/interface/src/app/map/map.component.spec.ts
  src/interface/src/app/navigation/navigation.component.spec.ts
  src/interface/src/app/plan/create-scenarios/set-priorities/set-priorities.component.spec.ts
  src/interface/src/app/plan/plan-map/plan-map.component.spec.ts
  src/interface/src/app/plan/plan-summary/scenario-configurations/scenario-configurations.component.spec.ts
  src/interface/src/app/plan/scenario-details/scenario-details.component.spec.ts
  src/interface/src/app/services/auth.service.spec.ts
  src/interface/src/app/shared/opacity-slider/opacity-slider.component.spec.ts
Labels: bug, frontend

#561 only sync visible maps
  src/interface/src/app/map/map-manager.ts
  src/interface/src/app/map/map.component.ts
Labels: enhancement, frontend

#565 Added mat-tabs to scenario details page and empty outcome component
  src/interface/src/app/plan/plan.module.ts
  src/interface/src/app/plan/scenario-details/outcome/outcome.component.html
  src/interface/src/app/plan/scenario-details/outcome/outcome.component.scss
  src/interface/src/app/plan/scenario-details/outcome/outcome.component.spec.ts
  src/interface/src/app/plan/scenario-details/outcome/outcome.component.ts
  src/interface/src/app/plan/scenario-details/scenario-details.component.html
  src/interface/src/app/plan/scenario-details/scenario-details.component.scss
Labels: enhancement, frontend

#568 Plan final step: generate scenario
  src/interface/src/app/plan/create-scenarios/create-scenarios.component.html
  src/interface/src/app/plan/create-scenarios/create-scenarios.component.spec.ts
  src/interface/src/app/plan/create-scenarios/create-scenarios.component.ts
  src/interface/src/app/plan/create-scenarios/generate-scenarios/generate-scenarios.component.html
  src/interface/src/app/plan/create-scenarios/generate-scenarios/generate-scenarios.component.spec.ts
  src/interface/src/app/plan/create-scenarios/generate-scenarios/generate-scenarios.component.ts
  src/interface/src/app/plan/plan.component.html
  src/interface/src/app/services/plan.service.spec.ts
  src/interface/src/app/services/plan.service.ts
  src/interface/src/app/types/plan.types.ts
Labels: enhancement, frontend, alpha

#570 Get real scenario from backend in scenario details component
  src/interface/src/app/plan/scenario-details/outcome/outcome.component.ts
  src/interface/src/app/plan/scenario-details/scenario-details.component.spec.ts
  src/interface/src/app/plan/scenario-details/scenario-details.component.ts
  src/interface/src/app/services/plan.service.spec.ts
  src/interface/src/app/services/plan.service.ts
  src/interface/src/app/types/plan.types.ts
Labels: enhancement, frontend

#572 Update plan state with config details and add routing
  src/interface/src/app/app-routing.module.ts
  src/interface/src/app/map/map.component.spec.ts
  src/interface/src/app/plan/create-scenarios/create-scenarios.component.html
  src/interface/src/app/plan/create-scenarios/create-scenarios.component.spec.ts
  src/interface/src/app/plan/create-scenarios/create-scenarios.component.ts
  src/interface/src/app/plan/plan-map/plan-map.component.spec.ts
  src/interface/src/app/plan/plan-map/plan-map.component.ts
  src/interface/src/app/plan/plan-summary/plan-overview/plan-overview.component.html
  src/interface/src/app/plan/plan-summary/plan-overview/plan-overview.component.spec.ts
  src/interface/src/app/plan/plan-summary/plan-overview/plan-overview.component.ts
  src/interface/src/app/plan/plan.component.html
  src/interface/src/app/plan/plan.component.spec.ts
  src/interface/src/app/plan/plan.component.ts
  src/interface/src/app/services/plan.service.ts
Labels: enhancement, frontend

#574 Display data from scenario and fake priorities
  src/interface/src/app/plan/scenario-details/outcome/outcome.component.html
  src/interface/src/app/plan/scenario-details/outcome/outcome.component.scss
  src/interface/src/app/plan/scenario-details/outcome/outcome.component.spec.ts
  src/interface/src/app/plan/scenario-details/outcome/outcome.component.ts
  src/interface/src/app/plan/scenario-details/scenario-details.component.html
  src/interface/src/app/plan/scenario-details/scenario-details.component.spec.ts
  src/interface/src/app/services/plan.service.ts
Labels: enhancement, frontend

#576 scenario generation confirmation page
  src/interface/src/app/app-routing.module.ts
  src/interface/src/app/plan/create-scenarios/create-scenarios.component.spec.ts
  src/interface/src/app/plan/create-scenarios/create-scenarios.component.ts
  src/interface/src/app/plan/plan.module.ts
  src/interface/src/app/plan/scenario-confirmation/scenario-confirmation.component.html
  src/interface/src/app/plan/scenario-confirmation/scenario-confirmation.component.scss
  src/interface/src/app/plan/scenario-confirmation/scenario-confirmation.component.spec.ts
  src/interface/src/app/plan/scenario-confirmation/scenario-confirmation.component.ts
Labels: enhancement, frontend

#592 Add Map Layers component to Scenario Details
  src/interface/src/app/plan/plan-map/plan-map.component.ts
  src/interface/src/app/plan/plan.module.ts
  src/interface/src/app/plan/scenario-details/map-layers/map-layers.component.html
  src/interface/src/app/plan/scenario-details/map-layers/map-layers.component.scss
  src/interface/src/app/plan/scenario-details/map-layers/map-layers.component.spec.ts
  src/interface/src/app/plan/scenario-details/map-layers/map-layers.component.ts
  src/interface/src/app/plan/scenario-details/scenario-details.component.html
  src/interface/src/app/plan/scenario-details/scenario-details.component.spec.ts
  src/interface/src/app/plan/scenario-details/scenario-details.component.ts
Labels: enhancement, frontend

#591 Update plan legend and panel toggle button
  src/interface/src/app/plan/create-scenarios/create-scenarios.component.ts
  src/interface/src/app/plan/create-scenarios/set-priorities/set-priorities.component.html
  src/interface/src/app/plan/create-scenarios/set-priorities/set-priorities.component.scss
  src/interface/src/app/plan/create-scenarios/set-priorities/set-priorities.component.spec.ts
  src/interface/src/app/plan/create-scenarios/set-priorities/set-priorities.component.ts
  src/interface/src/app/plan/plan-map/plan-map.component.html
  src/interface/src/app/plan/plan-map/plan-map.component.scss
  src/interface/src/app/plan/plan-map/plan-map.component.spec.ts
  src/interface/src/app/plan/plan-map/plan-map.component.ts
  src/interface/src/app/plan/scenario-details/scenario-details.component.ts
  src/interface/src/app/services/plan.service.ts
  src/interface/src/app/shared/legend/legend.component.html
  src/interface/src/app/shared/legend/legend.component.scss
  src/interface/src/app/types/legend.types.ts
Labels: enhancement, frontend
