Repository OurPlanscape/Planscape, pull requests merged in 2023-01, with the labels that each got.

#273 Tighten up AWS deployment
  .github/workflows/deploy_aws.yaml
  src/deployment/rds_postgis_setup.sql
  src/deployment/task_definition.json
  src/docker-compose.yaml
  src/interface/angular.json
  src/interface/nginx/nginx.conf
  src/planscape/Dockerfile
  src/planscape/planscape/settings.py
  src/task-definition.json
Labels: backend

#272 Add "create_project" API; only has "max_cost" constraint thus far
  src/planscape/plan/migrations/0003_project_scenario_generatedprojectareas.py
  src/planscape/plan/tests.py
  src/planscape/plan/urls.py
  src/planscape/plan/views.py
Labels: backend

#283 Plan table view
  src/interface/src/app/app-routing.module.ts
  src/interface/src/app/material/material.module.ts
  src/interface/src/app/navigation/navigation.component.ts
  src/interface/src/app/plan/plan-table/plan-table.component.html
  src/interface/src/app/plan/plan-table/plan-table.component.scss
  src/interface/src/app/plan/plan-table/plan-table.component.spec.ts
  src/interface/src/app/plan/plan-table/plan-table.component.ts
  src/interface/src/app/plan/plan.module.ts
  src/interface/src/app/services/plan.service.spec.ts
  src/interface/src/app/services/plan.service.ts
  src/interface/src/app/types/plan.types.ts
Labels: enhancement, frontend

#284 Add creation_time and # projects/scenarios to APIs
  src/planscape/plan/migrations/0004_plan_creation_time.py
  src/planscape/plan/models.py
  src/planscape/plan/serializers.py
  src/planscape/plan/tests.py
  src/planscape/plan/views.py
Labels: backend

#304 Add capability to push to AWS when a new GitHub release is built
  .github/workflows/deploy_aws.yaml
Labels: enhancement

#302 Fix #298 by setting z-index of road layer to 0
  src/interface/src/app/map/map-manager.ts
Labels: bug, frontend

#309 Minor refactor to plan components
  src/interface/src/app/plan/plan-summary/saved-scenarios/saved-scenarios.component.html
  src/interface/src/app/plan/plan-summary/saved-scenarios/saved-scenarios.component.scss
  src/interface/src/app/plan/plan-summary/saved-scenarios/saved-scenarios.component.spec.ts
  src/interface/src/app/plan/plan-summary/saved-scenarios/saved-scenarios.component.ts
  src/interface/src/app/plan/plan-summary/summary-panel/summary-panel.component.html
  src/interface/src/app/plan/plan-summary/summary-panel/summary-panel.component.scss
  src/interface/src/app/plan/plan-summary/summary-panel/summary-panel.component.spec.ts
  src/interface/src/app/plan/plan-summary/summary-panel/summary-panel.component.ts
  src/interface/src/app/plan/plan-summary/unsaved-scenarios/unsaved-scenarios.component.html
  src/interface/src/app/plan/plan-summary/unsaved-scenarios/unsaved-scenarios.component.scss
  src/interface/src/app/plan/plan-summary/unsaved-scenarios/unsaved-scenarios.component.spec.ts
  src/interface/src/app/plan/plan-summary/unsaved-scenarios/unsaved-scenarios.component.ts
  src/interface/src/app/plan/plan.module.ts
Labels: enhancement, frontend

#305 Tweaks to condition selection UI
  src/interface/src/app/map/map.component.html
  src/interface/src/app/map/map.component.scss
  src/interface/src/app/map/map.component.spec.ts
  src/interface/src/app/map/map.component.ts
Labels: bug, frontend

#323 Set priorities page (first pass)
  src/interface/src/app/material/material.module.ts
  src/interface/src/app/plan/create-scenarios/create-scenarios-intro/create-scenarios-intro.component.html
  src/interface/src/app/plan/create-scenarios/create-scenarios-intro/create-scenarios-intro.component.scss
  src/interface/src/app/plan/create-scenarios/create-scenarios-intro/create-scenarios-intro.component.spec.ts
  src/interface/src/app/plan/create-scenarios/create-scenarios-intro/create-scenarios-intro.component.ts
  src/interface/src/app/plan/create-scenarios/create-scenarios.component.html
  src/interface/src/app/plan/create-scenarios/create-scenarios.component.scss
  src/interface/src/app/plan/create-scenarios/create-scenarios.component.spec.ts
  src/interface/src/app/plan/create-scenarios/create-scenarios.component.ts
  src/interface/src/app/plan/create-scenarios/set-priorities/set-priorities.component.html
  src/interface/src/app/plan/create-scenarios/set-priorities/set-priorities.component.scss
  src/interface/src/app/plan/create-scenarios/set-priorities/set-priorities.component.spec.ts
  src/interface/src/app/plan/create-scenarios/set-priorities/set-priorities.component.ts
  src/interface/src/app/plan/plan-bottom-bar/plan-bottom-bar.component.html
  src/interface/src/app/plan/plan-bottom-bar/plan-bottom-bar.component.ts
  src/interface/src/app/plan/plan-map/plan-map.component.spec.ts
  src/interface/src/app/plan/plan-map/plan-map.component.ts
  src/interface/src/app/plan/plan.component.html
  src/interface/src/app/plan/plan.component.spec.ts
  src/interface/src/app/plan/plan.component.ts
  src/interface/src/app/plan/plan.module.ts
Labels: enhancement, frontend

#329 Tweak style for boundary shapes
  src/interface/src/app/map/map-manager.ts
Labels: bug, frontend

#328 Minor fixes to set priorities view
  src/interface/src/app/plan/create-scenarios/set-priorities/set-priorities.component.spec.ts
  src/interface/src/app/plan/create-scenarios/set-priorities/set-priorities.component.ts
  src/interface/src/app/plan/plan-map/plan-map.component.ts
Labels: bug, frontend

#358 remove boundary popups
  src/interface/src/app/map/map-manager.ts
  src/interface/src/app/map/map.component.spec.ts
  src/interface/src/app/map/project-card/project-card.component.html
  src/interface/src/app/map/project-card/project-card.component.spec.ts
  src/interface/src/app/map/project-card/project-card.component.ts
Labels: bug, frontend, fishfood/alpha

#330 Disable popups in explore when the user is drawing
  src/interface/src/app/map/map-manager.ts
  src/interface/src/app/map/map.component.spec.ts
Labels: bug, frontend

#360 remove 'potential for impact' from legend
  src/interface/src/app/shared/legend/legend.component.html
Labels: bug, frontend, fishfood/alpha

#361 cutoff fix for create scenario panel
  src/interface/src/app/plan/create-scenarios/create-scenarios-intro/create-scenarios-intro.component.html
  src/interface/src/app/plan/create-scenarios/create-scenarios-intro/create-scenarios-intro.component.scss
  src/interface/src/app/plan/create-scenarios/create-scenarios.component.scss
  src/interface/src/app/plan/create-scenarios/create-scenarios.component.ts
Labels: bug, frontend, fishfood/alpha

#362 default to 4 map view
  src/interface/src/app/map/map.component.spec.ts
  src/interface/src/app/types/map.types.ts
Labels: enhancement, frontend, fishfood/alpha

#364 More popup fixes
  src/interface/src/app/map/map-manager.ts
  src/interface/src/app/map/map.component.spec.ts
  src/interface/src/app/map/map.component.ts
  src/interface/src/app/map/project-card/project-card.component.ts
Labels: bug, frontend, fishfood/alpha

#370 in 2-map view, show row containing selected map
  src/interface/src/app/map/map.component.spec.ts
  src/interface/src/app/map/map.component.ts
Labels: bug, frontend, fishfood/alpha

#379 populate layer info card
  src/interface/src/app/map/layer-info-card/layer-info-card.component.html
  src/interface/src/app/map/layer-info-card/layer-info-card.component.ts
  src/interface/src/app/types/data.types.ts
Labels: bug, frontend, fishfood/alpha

#373 Constraints panel component
  src/interface/src/app/plan/create-scenarios/constraints-panel/constraints-panel.component.html
  src/interface/src/app/plan/create-scenarios/constraints-panel/constraints-panel.component.scss
  src/interface/src/app/plan/create-scenarios/constraints-panel/constraints-panel.component.spec.ts
  src/interface/src/app/plan/create-scenarios/constraints-panel/constraints-panel.component.ts
  src/interface/src/app/plan/create-scenarios/create-scenarios-intro/create-scenarios-intro.component.scss
  src/interface/src/app/plan/create-scenarios/create-scenarios.component.html
  src/interface/src/app/plan/create-scenarios/create-scenarios.component.scss
  src/interface/src/app/plan/create-scenarios/create-scenarios.component.ts
  src/interface/src/app/plan/plan.component.html
  src/interface/src/app/plan/plan.component.spec.ts
  src/interface/src/app/plan/plan.component.ts
  src/interface/src/app/plan/plan.module.ts
Labels: enhancement, frontend

#382 make tooltips follow the cursor
  src/interface/src/app/map/map-manager.ts
Labels: bug, frontend, fishfood/alpha

#381 center planning area in visible portion of map
  src/interface/src/app/plan/plan-map/plan-map.component.ts
  src/interface/src/app/plan/plan.component.html
Labels: bug, frontend, fishfood/alpha

#401 find and select layer options based on restored session
  src/interface/src/app/map/map.component.ts
Labels: bug, frontend, alpha phase 2

#402 Fix Angular tests
  src/interface/src/app/map/map.component.ts
  src/interface/src/app/plan/create-scenarios/constraints-panel/constraints-panel.component.spec.ts
  src/interface/src/app/plan/create-scenarios/constraints-panel/constraints-panel.component.ts
  src/interface/src/app/plan/create-scenarios/create-scenarios-intro/create-scenarios-intro.component.spec.ts
  src/interface/src/app/plan/create-scenarios/create-scenarios.component.spec.ts
  src/interface/src/app/plan/plan-bottom-bar/plan-bottom-bar.component.spec.ts
  src/interface/src/app/plan/plan-summary/saved-scenarios/saved-scenarios.component.spec.ts
  src/interface/src/app/plan/plan-summary/unsaved-scenarios/unsaved-scenarios.component.spec.ts
  src/interface/src/app/plan/plan-table/plan-table.component.spec.ts
  src/interface/src/app/plan/plan.component.spec.ts
  src/interface/src/app/plan/progress-panel/progress-panel.component.ts
  src/interface/src/app/services/auth.service.ts
  src/interface/src/app/services/map.service.spec.ts
  src/interface/src/app/shared/file-uploader/file-uploader.component.spec.ts
Labels: bug, frontend

#422 Show avg condition scores for a planning area
  src/interface/src/app/plan/create-scenarios/create-scenarios.component.html
  src/interface/src/app/plan/create-scenarios/set-priorities/set-priorities.component.html
  src/interface/src/app/plan/create-scenarios/set-priorities/set-priorities.component.scss
  src/interface/src/app/plan/create-scenarios/set-priorities/set-priorities.component.spec.ts
  src/interface/src/app/plan/create-scenarios/set-priorities/set-priorities.component.ts
  src/interface/src/app/services/plan.service.spec.ts
  src/interface/src/app/services/plan.service.ts
  src/interface/src/app/types/plan.types.ts
Labels: enhancement, frontend, alpha phase 2

#406 Display an error popup when plan fails to create
  src/interface/src/app/map/map.component.ts
  src/interface/src/app/services/plan.service.ts
Labels: frontend

#418 Track selected priorities and emit event
  src/interface/src/app/plan/create-scenarios/create-scenarios.component.html
  src/interface/src/app/plan/create-scenarios/create-scenarios.component.ts
  src/interface/src/app/plan/create-scenarios/set-priorities/set-priorities.component.html
  src/interface/src/app/plan/create-scenarios/set-priorities/set-priorities.component.spec.ts
  src/interface/src/app/plan/create-scenarios/set-priorities/set-priorities.component.ts
Labels: enhancement, frontend, alpha phase 2

#428 Updates to frontend authentication logic
  src/interface/src/app/account-dialog/account-dialog.component.html
  src/interface/src/app/account-dialog/account-dialog.component.spec.ts
  src/interface/src/app/account-dialog/account-dialog.component.ts
  src/interface/src/app/app.component.spec.ts
  src/interface/src/app/app.component.ts
  src/interface/src/app/navigation/navigation.component.scss
  src/interface/src/app/navigation/navigation.component.spec.ts
  src/interface/src/app/services/auth.service.spec.ts
  src/interface/src/app/services/auth.service.ts
Labels: bug, frontend, alpha phase 2

#449 reorganize layer controls
  src/interface/src/app/map/map.component.html
Labels: enhancement, frontend, alpha phase 3

#451 Fix frontend tests again
  src/interface/src/app/plan/plan-table/plan-table.component.spec.ts
  src/interface/src/app/services/auth.service.spec.ts
Labels: bug, frontend

#442 Quick and dirty migration of plan flow to stepper
  src/interface/src/app/material/material.module.ts
  src/interface/src/app/plan/create-scenarios/constraints-panel/constraints-panel.component.html
  src/interface/src/app/plan/create-scenarios/constraints-panel/constraints-panel.component.scss
  src/interface/src/app/plan/create-scenarios/create-scenarios-intro/create-scenarios-intro.component.html
  src/interface/src/app/plan/create-scenarios/create-scenarios-intro/create-scenarios-intro.component.scss
  src/interface/src/app/plan/create-scenarios/create-scenarios.component.html
  src/interface/src/app/plan/create-scenarios/create-scenarios.component.scss
  src/interface/src/app/plan/create-scenarios/create-scenarios.component.ts
  src/interface/src/app/plan/create-scenarios/set-priorities/set-priorities.component.html
  src/interface/src/app/plan/create-scenarios/set-priorities/set-priorities.component.scss
  src/interface/src/app/plan/plan-bottom-bar/plan-bottom-bar.component.html
  src/interface/src/app/plan/plan-bottom-bar/plan-bottom-bar.component.ts
  src/interface/src/app/plan/plan-navigation-bar/plan-navigation-bar.component.html
  src/interface/src/app/plan/plan-navigation-bar/plan-navigation-bar.component.scss
  src/interface/src/app/plan/plan-navigation-bar/plan-navigation-bar.component.spec.ts
  src/interface/src/app/plan/plan-navigation-bar/plan-navigation-bar.component.ts
  src/interface/src/app/plan/plan.component.html
  src/interface/src/app/plan/plan.component.spec.ts
  src/interface/src/app/plan/plan.component.ts
  src/interface/src/app/plan/plan.module.ts
  src/interface/src/app/plan/progress-panel/progress-panel.component.html
  src/interface/src/app/plan/progress-panel/progress-panel.component.scss
  src/interface/src/app/plan/progress-panel/progress-panel.component.spec.ts
  src/interface/src/app/plan/progress-panel/progress-panel.component.ts
Labels: enhancement, frontend, alpha phase 2

#458 Update legend and add opacity controls for data layer
  src/interface/src/app/map/map-manager.ts
  src/interface/src/app/map/map.component.html
  src/interface/src/app/map/map.component.scss
  src/interface/src/app/map/map.component.spec.ts
  src/interface/src/app/map/map.component.ts
  src/interface/src/app/plan/create-scenarios/create-scenarios-intro/create-scenarios-intro.component.html
  src/interface/src/app/shared/legend/legend.component.html
  src/interface/src/app/shared/legend/legend.component.scss
  src/interface/src/app/shared/legend/legend.component.ts
  src/interface/src/app/shared/opacity-slider/opacity-slider.component.html
  src/interface/src/app/shared/opacity-slider/opacity-slider.component.scss
  src/interface/src/app/shared/opacity-slider/opacity-slider.component.spec.ts
  src/interface/src/app/shared/opacity-slider/opacity-slider.component.ts
  src/interface/src/app/shared/shared.module.ts
  src/interface/src/app/types/data.types.ts
  src/interface/src/app/types/legend.types.ts
  src/interface/src/app/types/map.types.ts
Labels: enhancement, frontend, alpha phase 3
