Repository OurPlanscape/Planscape, pull requests merged in 2023-03, with the labels that each got.

#593 Plan overview UI and style changes
  src/interface/src/app/plan/plan-summary/plan-overview/plan-overview.component.scss
  src/interface/src/app/plan/plan-summary/saved-scenarios/saved-scenarios.component.html
  src/interface/src/app/plan/plan-summary/saved-scenarios/saved-scenarios.component.scss
  src/interface/src/app/plan/plan-summary/saved-scenarios/saved-scenarios.component.spec.ts
  src/interface/src/app/plan/plan-summary/saved-scenarios/saved-scenarios.component.ts
  src/interface/src/app/plan/plan-summary/scenario-configurations/scenario-configurations.component.html
  src/interface/src/app/plan/plan-summary/scenario-configurations/scenario-configurations.component.scss
  src/interface/src/app/plan/plan-summary/scenario-configurations/scenario-configurations.component.ts
  src/interface/src/app/plan/plan.component.scss
Labels: enhancement, frontend

#598 Favorite scenario backend API + frontend change
  src/interface/src/app/plan/plan-summary/saved-scenarios/saved-scenarios.component.html
  src/interface/src/app/plan/plan-summary/saved-scenarios/saved-scenarios.component.spec.ts
  src/interface/src/app/plan/plan-summary/saved-scenarios/saved-scenarios.component.ts
  src/interface/src/app/services/plan.service.spec.ts
  src/interface/src/app/services/plan.service.ts
  src/interface/src/app/types/plan.types.ts
  src/planscape/plan/migrations/0016_scenario_favorited.py
  src/planscape/plan/models.py
  src/planscape/plan/tests.py
  src/planscape/plan/urls.py
  src/planscape/plan/views.py
Labels: enhancement, frontend, backend

#595 Delete scenarios backend API + frontend change
  src/interface/src/app/plan/plan-summary/saved-scenarios/saved-scenarios.component.spec.ts
  src/interface/src/app/plan/plan-summary/saved-scenarios/saved-scenarios.component.ts
  src/interface/src/app/services/plan.service.spec.ts
  src/interface/src/app/services/plan.service.ts
  src/planscape/plan/tests.py
  src/planscape/plan/urls.py
  src/planscape/plan/views.py
Labels: enhancement, frontend, backend

#604 add data units to layer info card
  src/interface/src/app/map/layer-info-card/layer-info-card.component.html
  src/interface/src/app/map/layer-info-card/layer-info-card.component.ts
  src/interface/src/app/types/data.types.ts
Labels: enhancement, frontend

#605 Create uploaded project area upon generating scenario
  src/interface/src/app/plan/create-scenarios/create-scenarios.component.html
  src/interface/src/app/plan/create-scenarios/create-scenarios.component.spec.ts
  src/interface/src/app/plan/create-scenarios/create-scenarios.component.ts
  src/interface/src/app/services/plan.service.spec.ts
  src/interface/src/app/services/plan.service.ts
Labels: frontend

#632 disable descendants checkboxes when a priority is selected
  src/interface/src/app/plan/create-scenarios/set-priorities/set-priorities.component.html
  src/interface/src/app/plan/create-scenarios/set-priorities/set-priorities.component.spec.ts
  src/interface/src/app/plan/create-scenarios/set-priorities/set-priorities.component.ts
Labels: bug, frontend

#633 Add project area information to scenario details outcome tab
  src/interface/src/app/plan/scenario-details/outcome/outcome.component.html
  src/interface/src/app/plan/scenario-details/outcome/outcome.component.scss
  src/interface/src/app/plan/scenario-details/outcome/outcome.component.spec.ts
  src/interface/src/app/plan/scenario-details/outcome/outcome.component.ts
  src/interface/src/app/services/plan.service.spec.ts
  src/interface/src/app/services/plan.service.ts
  src/interface/src/app/types/plan.types.ts
Labels: frontend

#636 Add "Clear All" button to map layer controls
  src/interface/src/app/map/map-control-panel/map-control-panel.component.html
  src/interface/src/app/map/map-control-panel/map-control-panel.component.scss
  src/interface/src/app/map/map-control-panel/map-control-panel.component.spec.ts
  src/interface/src/app/map/map-control-panel/map-control-panel.component.ts
Labels: enhancement, frontend

#642 Small fix for converting project areas from backend response
  src/interface/src/app/services/plan.service.ts
Labels: frontend

#644 change map highlight color and thickness
  src/interface/src/app/map/map.component.scss
Labels: enhancement, frontend

#645 fix z-index for basemaps
  src/interface/src/app/map/map-manager.ts
Labels: bug, frontend

#647 re-enabled scroll to zoom
  src/interface/src/app/map/map-manager.ts
Labels: enhancement, frontend

#648 update create plan dialog strings and styling
  src/interface/src/app/map/plan-create-dialog/plan-create-dialog.component.html
  src/interface/src/app/map/plan-create-dialog/plan-create-dialog.component.scss
Labels: enhancement, frontend

#646 sort plans by date descending
  src/interface/src/app/plan/plan-table/plan-table.component.spec.ts
  src/interface/src/app/plan/plan-table/plan-table.component.ts
Labels: enhancement, frontend

#649 Display project areas on the map in Scenario Details view
  src/interface/src/app/plan/plan-map/plan-map.component.spec.ts
  src/interface/src/app/plan/plan-map/plan-map.component.ts
  src/interface/src/app/plan/plan.component.spec.ts
  src/interface/src/app/plan/plan.component.ts
  src/interface/src/app/plan/scenario-details/scenario-details.component.spec.ts
  src/interface/src/app/plan/scenario-details/scenario-details.component.ts
  src/interface/src/app/services/plan.service.ts
Labels: frontend

#653 Use actual priorities fetched from scenario in Scenario Details
  src/interface/src/app/plan/scenario-details/outcome/outcome.component.html
  src/interface/src/app/plan/scenario-details/outcome/outcome.component.ts
  src/interface/src/app/services/plan.service.spec.ts
  src/interface/src/app/services/plan.service.ts
  src/interface/src/app/types/plan.types.ts
Labels: frontend

#652 Add homepage containing region selection and plan table
  src/interface/src/app/app-routing.module.ts
  src/interface/src/app/app.module.ts
  src/interface/src/app/home/home.component.html
  src/interface/src/app/home/home.component.scss
  src/interface/src/app/home/home.component.spec.ts
  src/interface/src/app/home/home.component.ts
  src/interface/src/app/home/plan-table/delete-plan-dialog/delete-plan-dialog.component.html
  src/interface/src/app/home/plan-table/delete-plan-dialog/delete-plan-dialog.component.scss
  src/interface/src/app/home/plan-table/delete-plan-dialog/delete-plan-dialog.component.spec.ts
  src/interface/src/app/home/plan-table/delete-plan-dialog/delete-plan-dialog.component.ts
  src/interface/src/app/home/plan-table/plan-table.component.html
  src/interface/src/app/home/plan-table/plan-table.component.scss
  src/interface/src/app/home/plan-table/plan-table.component.spec.ts
  src/interface/src/app/home/plan-table/plan-table.component.ts
  src/interface/src/app/home/region-selection/region-selection.component.html
  src/interface/src/app/home/region-selection/region-selection.component.scss
  src/interface/src/app/home/region-selection/region-selection.component.spec.ts
  src/interface/src/app/home/region-selection/region-selection.component.ts
  src/interface/src/app/navigation/navigation.component.ts
  src/interface/src/app/plan/plan-table/plan-table.component.html
  src/interface/src/app/plan/plan-table/plan-table.component.scss
  src/interface/src/app/plan/plan.module.ts
  src/interface/src/app/region-selection/region-selection.component.html
  src/interface/src/app/region-selection/region-selection.component.scss
  src/interface/src/app/region-selection/region-selection.component.spec.ts
  src/interface/src/app/top-bar/top-bar.component.html
  src/interface/src/assets/png/planscape_home_bg.png
Labels: enhancement, frontend

#659 Use actual config data in Scenario Details
  src/interface/src/app/plan/plan-summary/saved-scenarios/saved-scenarios.component.spec.ts
  src/interface/src/app/plan/scenario-details/outcome/outcome.component.html
  src/interface/src/app/plan/scenario-details/outcome/outcome.component.spec.ts
  src/interface/src/app/plan/scenario-details/outcome/outcome.component.ts
  src/interface/src/app/plan/scenario-details/scenario-details.component.spec.ts
  src/interface/src/app/services/plan.service.spec.ts
  src/interface/src/app/services/plan.service.ts
  src/interface/src/app/types/plan.types.ts
Labels: frontend

#661 Update side navigation bar
  src/interface/src/app/navigation/navigation.component.html
  src/interface/src/app/navigation/navigation.component.scss
Labels: enhancement, frontend

#663 Revamp login page
  src/interface/src/app/login/login.component.html
  src/interface/src/app/login/login.component.scss
  src/interface/src/app/login/login.component.spec.ts
  src/interface/src/app/login/login.component.ts
  src/interface/src/assets/png/planscape_signin_bg.png
Labels: enhancement, frontend

#684 show username of logged in user in top bar
  src/interface/src/app/top-bar/top-bar.component.html
  src/interface/src/app/top-bar/top-bar.component.scss
  src/interface/src/app/top-bar/top-bar.component.spec.ts
  src/interface/src/app/top-bar/top-bar.component.ts
Labels: enhancement, frontend

#685 fix placement of logout link
  src/interface/src/app/navigation/navigation.component.html
Labels: bug, frontend

#694 Revamp registration page
  src/interface/src/app/signup/signup.component.html
  src/interface/src/app/signup/signup.component.scss
  src/interface/src/app/signup/signup.component.spec.ts
  src/interface/src/app/signup/signup.component.ts
  src/interface/src/index.html
Labels: enhancement, frontend

#697 Limit frontend features for logged out users to region selection + explore
  src/interface/src/app/app-routing.module.ts
  src/interface/src/app/app.module.ts
  src/interface/src/app/home/plan-table/plan-table.component.html
  src/interface/src/app/home/plan-table/plan-table.component.ts
  src/interface/src/app/home/region-selection/region-selection.component.html
  src/interface/src/app/home/region-selection/region-selection.component.scss
  src/interface/src/app/home/region-selection/region-selection.component.ts
  src/interface/src/app/map/map.component.spec.ts
  src/interface/src/app/map/map.component.ts
  src/interface/src/app/map/sign-in-dialog/sign-in-dialog.component.html
  src/interface/src/app/map/sign-in-dialog/sign-in-dialog.component.scss
  src/interface/src/app/map/sign-in-dialog/sign-in-dialog.component.spec.ts
  src/interface/src/app/map/sign-in-dialog/sign-in-dialog.component.ts
  src/interface/src/app/services/auth.service.spec.ts
  src/interface/src/app/services/auth.service.ts
Labels: enhancement, frontend

#721 fix font import error
  src/interface/src/index.html
Labels: bug, frontend

#695 User changes
  src/interface/src/app/account-dialog/account-dialog.component.html
  src/interface/src/app/account-dialog/account-dialog.component.spec.ts
  src/interface/src/app/account-dialog/account-dialog.component.ts
  src/interface/src/app/home/region-selection/region-selection.component.ts
  src/interface/src/app/plan/scenario-details/outcome/outcome.component.spec.ts
  src/interface/src/app/plan/scenario-details/outcome/outcome.component.ts
  src/interface/src/app/services/auth.service.spec.ts
  src/interface/src/app/services/auth.service.ts
  src/interface/src/app/signup/signup.component.html
  src/interface/src/app/signup/signup.component.spec.ts
  src/interface/src/app/signup/signup.component.ts
  src/interface/src/app/top-bar/top-bar.component.html
  src/interface/src/app/top-bar/top-bar.component.spec.ts
  src/interface/src/app/top-bar/top-bar.component.ts
  src/interface/src/app/types/index.ts
  src/interface/src/app/types/user.types.ts
  src/planscape/planscape/settings.py
  src/planscape/users/__init__.py
  src/planscape/users/admin.py
  src/planscape/users/apps.py
  src/planscape/users/migrations/__init__.py
  src/planscape/users/models.py
  src/planscape/users/serializers.py
  src/planscape/users/tests.py
  src/planscape/users/views.py
Labels: enhancement, frontend, backend

#712 style changes to map layer panel
  src/interface/src/app/map/map-control-panel/condition-tree/condition-tree.component.html
  src/interface/src/app/map/map-control-panel/condition-tree/condition-tree.component.scss
  src/interface/src/app/map/map-control-panel/condition-tree/condition-tree.component.spec.ts
  src/interface/src/app/map/map-control-panel/condition-tree/condition-tree.component.ts
  src/interface/src/app/map/map-control-panel/map-control-panel.component.html
  src/interface/src/app/map/map-control-panel/map-control-panel.component.ts
Labels: enhancement, frontend

#700 change constraint form logic and add estimated cost
  src/interface/src/app/plan/create-scenarios/constraints-panel/constraints-panel.component.html
  src/interface/src/app/plan/create-scenarios/constraints-panel/constraints-panel.component.scss
  src/interface/src/app/plan/create-scenarios/constraints-panel/constraints-panel.component.spec.ts
  src/interface/src/app/plan/create-scenarios/constraints-panel/constraints-panel.component.ts
  src/interface/src/app/plan/create-scenarios/create-scenarios.component.spec.ts
  src/interface/src/app/plan/create-scenarios/create-scenarios.component.ts
  src/interface/src/app/services/plan.service.spec.ts
  src/interface/src/app/services/plan.service.ts
  src/interface/src/app/types/plan.types.ts
Labels: enhancement, frontend

#722 Fix for incorrect priority weights
  src/interface/src/app/plan/scenario-details/outcome/outcome.component.html
  src/interface/src/app/services/plan.service.ts
Labels: bug, frontend

#728 use project_id in createScenario
  src/interface/src/app/services/plan.service.spec.ts
  src/interface/src/app/services/plan.service.ts
Labels: enhancement, frontend

#696 add form validation to login
  src/interface/src/app/login/login.component.html
  src/interface/src/app/login/login.component.spec.ts
  src/interface/src/app/login/login.component.ts
Labels: enhancement, frontend

#729 Updated drawing UI in explore map to new mocks
  src/interface/src/app/map/map.component.html
  src/interface/src/app/map/map.component.scss
  src/interface/src/app/map/map.component.spec.ts
  src/interface/src/app/map/map.component.ts
Labels: frontend

#731 Update planning area and project area colors
  src/interface/src/app/plan/plan-map/plan-map.component.spec.ts
  src/interface/src/app/plan/plan-map/plan-map.component.ts
Labels: frontend

#730 Add account management dialog
  src/interface/src/app/account-dialog/account-dialog.component.html
  src/interface/src/app/account-dialog/account-dialog.component.scss
  src/interface/src/app/account-dialog/account-dialog.component.spec.ts
  src/interface/src/app/account-dialog/account-dialog.component.ts
  src/interface/src/app/services/auth.service.spec.ts
  src/interface/src/app/services/auth.service.ts
  src/planscape/planscape/settings.py
Labels: enhancement, frontend

#732 Allow user to update scenario notes
  src/interface/src/app/plan/scenario-details/outcome/outcome.component.html
  src/interface/src/app/plan/scenario-details/outcome/outcome.component.spec.ts
  src/interface/src/app/plan/scenario-details/outcome/outcome.component.ts
  src/interface/src/app/plan/scenario-details/scenario-details.component.ts
  src/interface/src/app/services/plan.service.spec.ts
  src/interface/src/app/services/plan.service.ts
  src/planscape/plan/views.py
Labels: frontend

#733 Update scenario details to show more info
  src/interface/src/app/plan/scenario-details/outcome/outcome.component.html
  src/interface/src/app/plan/scenario-details/outcome/outcome.component.spec.ts
  src/interface/src/app/plan/scenario-details/outcome/outcome.component.ts
  src/interface/src/app/plan/scenario-details/scenario-details.component.html
  src/interface/src/app/types/plan.types.ts
Labels: frontend

#736 hide panel toggle button from plan summary page
  src/interface/src/app/plan/plan-map/plan-map.component.html
  src/interface/src/app/plan/plan-map/plan-map.component.spec.ts
  src/interface/src/app/plan/plan-map/plan-map.component.ts
Labels: bug, frontend

#741 Delete account UI + functionality
  src/interface/src/app/account-dialog/account-dialog.component.html
  src/interface/src/app/account-dialog/account-dialog.component.spec.ts
  src/interface/src/app/account-dialog/account-dialog.component.ts
  src/interface/src/app/account-dialog/delete-account-dialog/delete-account-dialog.component.html
  src/interface/src/app/account-dialog/delete-account-dialog/delete-account-dialog.component.scss
  src/interface/src/app/account-dialog/delete-account-dialog/delete-account-dialog.component.spec.ts
  src/interface/src/app/account-dialog/delete-account-dialog/delete-account-dialog.component.ts
  src/interface/src/app/app.module.ts
  src/interface/src/app/services/auth.service.spec.ts
  src/interface/src/app/services/auth.service.ts
  src/planscape/planscape/urls.py
  src/planscape/users/tests.py
  src/planscape/users/urls.py
  src/planscape/users/views.py
Labels: enhancement, frontend, backend

#747 set allowed headers and cookie settings
  src/planscape/planscape/settings.py
Labels: bug, backend

#750 Remove create scenarios button in plan overview
  src/interface/src/app/plan/plan-summary/saved-scenarios/saved-scenarios.component.html
  src/interface/src/app/plan/plan-summary/saved-scenarios/saved-scenarios.component.spec.ts
  src/interface/src/app/plan/plan-summary/saved-scenarios/saved-scenarios.component.ts
Labels: frontend

#751 add explicit versions to auth pkgs in requirements.txt
  src/planscape/requirements.txt
Labels: bug

#748 Update plan summary to new mocks and add get_user_by_id endpoint
  src/interface/src/app/plan/plan-summary/summary-panel/summary-panel.component.html
  src/interface/src/app/plan/plan-summary/summary-panel/summary-panel.component.scss
  src/interface/src/app/plan/plan-summary/summary-panel/summary-panel.component.ts
  src/interface/src/app/plan/plan.component.html
  src/interface/src/app/plan/plan.component.spec.ts
  src/interface/src/app/plan/plan.component.ts
  src/interface/src/app/services/auth.service.spec.ts
  src/interface/src/app/services/auth.service.ts
  src/interface/src/app/services/plan.service.spec.ts
  src/interface/src/app/services/plan.service.ts
  src/interface/src/app/types/plan.types.ts
  src/planscape/users/serializers.py
  src/planscape/users/urls.py
  src/planscape/users/views.py
Labels: frontend, backend

#754 upgrade to dj-rest-auth v3.0.0
  src/planscape/planscape/settings.py
  src/planscape/requirements.txt
Labels: enhancement, backend
